name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dump .env file (optional)
        run: |
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "API_IDENTIFIER=${{ secrets.API_IDENTIFIER }}" >> .env
          echo "ALGORITHMS=${{ secrets.ALGORITHMS }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> .env

      - name: Install Render CLI
        run: npm install -g render-cli

      - name: Deploy using Render CLI
        run:
          render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }} --api-key
          ${{ secrets.RENDER_API_KEY }}
